from pathlib import Path

from docx import Document
from docx.oxml import OxmlElement


SOURCE = Path("documentacion/TESIS_AGO2026_Rev39_(ZUJ)_22ago2026_JustificacionAlineada.docx")
OUTPUT = Path("documentacion/TESIS_AGO2026_Rev40_(ZUJ)_24ago2026_HorizonteSemanal.docx")
NEW_TITLE = (
    "PRONÓSTICO SEMANAL DEL PRESUPUESTO DE ABASTECIMIENTO MEDIANTE MODELOS "
    "ESTADÍSTICOS Y APRENDIZAJE AUTOMÁTICO CON VALIDACIÓN DE VENTANA DESLIZANTE: "
    "ESTUDIO DE CASO EN UNA MICROEMPRESA DE REPOSTERÍA CREATIVA DE TIZAYUCA, HIDALGO"
)


def set_text(paragraph, text):
    paragraph.runs[0].text = text
    for run in paragraph.runs[1:]:
        run.text = ""


def find(prefix):
    matches = [p for p in document.paragraphs if p.text.strip().startswith(prefix)]
    if len(matches) != 1:
        raise RuntimeError(f"No se encontró un único párrafo para: {prefix!r} ({len(matches)})")
    return matches[0]


def insert_after(paragraph, text, style):
    added = paragraph._parent.add_paragraph()
    added._p.getparent().remove(added._p)
    paragraph._p.addnext(added._p)
    added.style = style
    added.add_run(text)
    return added


document = Document(SOURCE)
set_text(find("“PREDICCIÓN DEL PRESUPUESTO DE ABASTECIMIENTO"), NEW_TITLE)

replacements = [
    ("La investigación desarrolló y evaluó modelos predictivos", "La investigación evalúa modelos predictivos para pronosticar semanalmente el presupuesto de abastecimiento de Cup&Cake, microempresa de repostería ubicada en Tizayuca, Hidalgo. A partir de registros diarios de ventas y compras se construirá un dataset semanal, integrado con variables calendáricas, económicas y climáticas disponibles antes del periodo pronosticado. La evaluación utilizará validación temporal mediante ventana deslizante y comparación contra líneas base empíricas y modelos estadísticos de referencia."),
    ("El dataset maestro quedó conformado", "El estudio comparará modelos estadísticos y de aprendizaje automático para pronosticar el importe semanal de compras a uno y, de manera complementaria, cuatro periodos hacia adelante. Los pronósticos semanales permitirán integrar una estimación mensual del presupuesto de abastecimiento. Los resultados se comunicarán mediante un sistema de soporte a la decisión con indicadores, filtros y salvaguardas de interpretación humana."),
    ("This research developed and evaluated predictive models", "This research evaluates predictive models for weekly procurement-budget forecasting at Cup&Cake, a small bakery in Tizayuca, Hidalgo. Daily sales and purchasing records will be aggregated into a weekly dataset and complemented with calendar, economic, and weather variables available before the forecast period. Models will be assessed through sliding-window temporal validation against empirical baselines and statistical reference models. Weekly forecasts will support one- to four-week planning and a monthly budget consolidation through a business-intelligence decision-support dashboard."),
    ("(Makridakis et al., 2018; Spiliotis et al., 2025)", "La literatura reciente muestra que los modelos de aprendizaje automático pueden capturar relaciones no lineales, estacionalidad y variables externas; sin embargo, su desempeño frente a los métodos estadísticos depende de las características de la serie, la disponibilidad de datos, el horizonte de pronóstico y el protocolo de evaluación (Makridakis et al., 2018; Spiliotis et al., 2022)."),
    ("Las series diarias de ventas y compras", "Los registros diarios de ventas y compras en negocios de pequeña escala pueden contener numerosos periodos sin movimiento y picos asociados a pedidos, fechas comerciales o reposiciones. Al agregarlos semanalmente, la serie puede reducir su intermitencia y ofrecer una unidad más congruente con la planeación de corto plazo; sin embargo, disminuye el número de observaciones disponibles. Por ello, los modelos de aprendizaje automático deben compararse con métodos estadísticos establecidos y no asumirse superiores por su mayor complejidad (Spiliotis et al., 2022)."),
    ("La evidencia identificada es limitada respecto de comparaciones temporales reproducibles", "La evidencia identificada es limitada respecto de comparaciones temporales reproducibles entre reglas empíricas, modelos estadísticos y aprendizaje automático para pronosticar semanalmente el importe de compras en microempresas de repostería con datos escasos e intermitentes."),
    ("En este sentido, la presente investigación contribuye", "En este sentido, la presente investigación contribuye mediante un estudio de caso aplicado en Cup&Cake, microempresa de repostería creativa en Tizayuca, Hidalgo. Integra registros históricos diarios de ventas y compras en una unidad semanal, usa validación de ventana deslizante y compara líneas base empíricas, modelos estadísticos y modelos de aprendizaje automático para pronosticar el importe semanal de compras. Su contribución se limita de forma explícita al apoyo del presupuesto de abastecimiento, sin inferir automáticamente una reducción de merma, inventario o rentabilidad."),
    ("El reto de Cup&Cake es mejorar su capacidad", "El reto de Cup&Cake es fortalecer la planeación semanal del presupuesto de abastecimiento. Para ello, requiere estimar al inicio de cada semana el importe probable de compras de las siguientes una a cuatro semanas, considerando el comportamiento histórico, las fechas comerciales y las variables exógenas disponibles."),
    ("Adicionalmente, al pronosticar metodológicamente", "El pronóstico tendrá como propósito reducir la incertidumbre al reservar y revisar el presupuesto de abastecimiento de corto plazo. La investigación no pretende medir directamente incrementos de utilidad, expansión comercial o reducción de costos, pues dichas conclusiones requerirían información adicional y un diseño de evaluación operativa."),
    ("¿En qué medida los modelos de aprendizaje automático, entrenados", "¿En qué medida los modelos estadísticos y de aprendizaje automático mejoran la precisión del pronóstico semanal del importe de compras de una microempresa de repostería creativa en Tizayuca, Hidalgo, frente a reglas empíricas reproducibles, para apoyar su presupuesto de abastecimiento?"),
    ("Evaluar en qué medida los modelos de aprendizaje automático", "Evaluar el desempeño de modelos estadísticos y de aprendizaje automático para pronosticar semanalmente el importe de compras de una microempresa de repostería creativa, frente a reglas empíricas y mediante validación temporal de ventana deslizante, con el propósito de apoyar la planeación del presupuesto de abastecimiento."),
    ("Describir los registros históricos de ventas y compras", "Describir y depurar los registros históricos diarios de ventas y compras, así como operacionalizar líneas base empíricas reproducibles de pronóstico semanal."),
    ("Construir un dataset maestro diario", "Construir un dataset semanal a partir de los registros diarios de ventas y compras, incorporando variables temporales y exógenas disponibles antes del periodo de pronóstico."),
    ("Emplear métodos estadísticos y modelos de aprendizaje automático para predecir", "Emplear métodos estadísticos y modelos de aprendizaje automático para predecir el importe semanal de compras a uno y, de manera complementaria, cuatro periodos hacia adelante."),
    ("Comparar el desempeño de los modelos mediante partición temporal", "Comparar el desempeño de los modelos mediante validación temporal de ventana deslizante, con el fin de identificar la alternativa con mayor precisión y estabilidad predictiva en condiciones de actualización continua."),
    ("Seleccionar la configuración predictiva con base", "Seleccionar la configuración predictiva con base en el ajuste de hiperparámetros, la selección de características, el desempeño fuera de muestra, la estabilidad y la interpretabilidad."),
    ("Contrastar los modelos de aprendizaje automático con la línea base", "Contrastar los modelos con las líneas base empíricas semanales mediante RMSE, MAE y una métrica escalada; usar MAPE sólo como diagnóstico complementario cuando la presencia de valores cero permita una interpretación válida."),
    ("Integrar los resultados en un tablero", "Integrar los resultados en un tablero de inteligencia de negocios para apoyar la consulta del presupuesto de abastecimiento de las próximas una a cuatro semanas y su consolidado mensual."),
    ("La relevancia social de esta investigación radica", "La relevancia social de esta investigación radica en aportar evidencia aplicada sobre el uso de modelos predictivos semanales en una microempresa con recursos de datos limitados. Las microempresas enfrentan restricciones financieras, tecnológicas y de capital humano que dificultan la adopción de herramientas analíticas; por ello, evaluar modelos con registros internos contribuye a identificar alternativas técnicamente accesibles para apoyar decisiones basadas en datos (Alekseeva et al., 2021; Poveda-Valverde & Fierro Barragán, 2026)."),
    ("En el caso de Cup&Cake, la investigación permite valorar", "En el caso de Cup&Cake, la investigación permite valorar si los modelos predictivos mejoran la anticipación semanal del presupuesto de abastecimiento frente a referencias empíricas y estadísticas. Aunque el estudio no mide directamente merma, inventarios ni rentabilidad, una predicción semanal más precisa puede constituir un insumo para decisiones más informadas en negocios con productos perecederos."),
    ("La investigación es conveniente porque responde", "La investigación es conveniente porque responde a una necesidad operativa concreta de Cup&Cake: estimar semanalmente el importe de compras de las siguientes una a cuatro semanas a partir de registros históricos. La disponibilidad de estas fuentes permite construir y evaluar un sistema predictivo sin requerir infraestructura corporativa ni datos externos indispensables."),
    ("Su conveniencia metodológica consiste", "Su conveniencia metodológica consiste en comparar modelos estadísticos y de aprendizaje automático con líneas base empíricas semanales mediante una ventana deslizante. Este contraste permite identificar si la complejidad algorítmica aporta una mejora verificable de precisión o si un método más simple resulta suficiente para el objetivo evaluado (Makridakis et al., 2018; Spiliotis et al., 2022)."),
    ("Desde el punto de vista teórico", "Desde el punto de vista teórico, la investigación contribuye al estudio del pronóstico semanal en contextos de Small Data e intermitencia. La literatura muestra que el desempeño de los modelos depende de la calidad y cantidad de datos, la granularidad de la serie, las variables disponibles y el protocolo de evaluación; por tanto, su superioridad no debe suponerse sin comparación empírica (Hewamalage et al., 2021; Giannopoulos et al., 2025)."),
    ("El estudio aporta evidencia comparativa en una microempresa", "El estudio aporta evidencia comparativa en una microempresa de repostería creativa al contrastar líneas base empíricas, modelos estadísticos y modelos de aprendizaje automático mediante validación temporal de ventana deslizante. Asimismo, permite examinar si las variables exógenas disponibles antes del pronóstico aportan información adicional para anticipar el presupuesto semanal de abastecimiento."),
    ("En términos prácticos, la investigación ofrece", "En términos prácticos, la investigación ofrece un procedimiento reproducible para integrar registros diarios, agregarlos semanalmente, generar variables temporales y evaluar modelos mediante métricas de error fuera de muestra. Los resultados se comunicarán en un tablero de inteligencia de negocios que permita consultar el importe semanal esperado de compras y su consolidado mensual."),
    ("El tablero funciona como apoyo", "El tablero funcionará como apoyo para revisar y reservar el presupuesto de abastecimiento; no generará órdenes automáticas de compra ni calculará cantidades físicas por insumo. Estas funciones requerirían información adicional sobre recetas, inventario, merma, costos de faltante, tiempos de entrega y unidades de medida homologadas."),
    ("En conjunto, la investigación se justifica", "En conjunto, la investigación se justifica por su aporte aplicado y metodológico: evalúa de manera rigurosa si los modelos estadísticos y de aprendizaje automático mejoran el pronóstico semanal del importe de compras en una microempresa, frente a referencias empíricas. Su contribución se limita al apoyo del presupuesto de abastecimiento y evita atribuir efectos no medidos sobre inventarios, merma, rentabilidad o expansión comercial."),
]

for prefix, text in replacements:
    set_text(find(prefix), text)

h1 = find("Al menos un modelo de aprendizaje automático reducirá")
set_text(h1, "H1. Al menos una configuración predictiva basada en modelos estadísticos o de aprendizaje automático, entrenada con información histórica semanal y variables exógenas disponibles al momento del pronóstico, presentará un error de pronóstico significativamente menor que la línea base primaria de último valor semanal observado para estimar el importe semanal de compras de la microempresa.")
h2_heading = insert_after(h1, "Hipótesis de investigación (H2)", "Heading 4")
insert_after(h2_heading, "H2. La inclusión de variables exógenas calendáricas, comerciales, económicas y climáticas disponibles antes del periodo pronosticado mejorará el desempeño de los modelos semanales respecto de configuraciones equivalentes basadas únicamente en información histórica.", "Normal")

anchor = find("La revisión de Giannopoulos et al. (2025)")
heading = insert_after(anchor, "Agregación temporal y horizonte de planeación", "Heading 3")
insert_after(heading, "La elección del horizonte debe responder a la frecuencia efectiva de decisión. En esta investigación, los registros diarios se agregan por semana calendario para apoyar la planeación del presupuesto de abastecimiento de corto plazo. La agregación semanal puede reducir ruido e intermitencia, aunque también disminuye el número de observaciones; por ello, la evaluación debe privilegiar modelos parsimoniosos y validación temporal estricta. El consolidado mensual se obtendrá a partir de los pronósticos semanales, sin asumir que existe un modelo mensual independiente con evidencia suficiente.", "Normal")

# Marco teórico: horizonte semanal, modelos pertinentes y rolling-window.
marco_replacements = [
    ("Investigaciones derivadas de las competencias de pronóstico M4", "Las competencias de pronóstico M4 y M5 muestran que los modelos estadísticos, los algoritmos de aprendizaje automático y sus combinaciones pueden ser competitivos cuando se incorporan variables exógenas y estacionales; sin embargo, su desempeño depende de la escala de la serie, el horizonte de pronóstico y el protocolo de evaluación (Makridakis, Spiliotis, & Assimakopoulos, 2020)."),
    ("A pesar de su robustez teórica y de haber gobernado", "Los enfoques estadísticos clásicos no deben asumirse como suficientes ni como inadecuados por definición. Su desempeño depende de la estabilidad de la serie, la estacionalidad, la longitud del historial y la presencia de variables exógenas; por ello, deben contrastarse empíricamente con los demás modelos bajo las mismas condiciones temporales."),
    ("En el ecosistema operativo de una microempresa como Cup&Cake", "En una microempresa como Cup&Cake pueden existir cambios de comportamiento, picos por eventos y relaciones no lineales entre ventas, compras y calendario. Estas características justifican comparar modelos estadísticos con algoritmos de aprendizaje automático, sin presuponer que una familia será superior en todos los horizontes o variables objetivo."),
    ("La literatura científica más reciente en la gestión de cadenas", "Las arquitecturas recurrentes y los modelos de aprendizaje profundo pueden capturar dependencias temporales complejas; no obstante, su utilidad debe contrastarse con alternativas más parsimoniosas cuando el número de observaciones semanales es limitado. En esta investigación, RNN y LSTM se consideran modelos de comparación secundaria, no una solución presuntamente superior."),
    ("Protocolos estrictos de validación temporal (como la metodología", "Protocolos estrictos de validación temporal mediante rolling-window (ventana deslizante)."),
    ("Al sincronizar estos pronósticos avanzados con herramientas", "Al integrar los pronósticos con herramientas de inteligencia de negocios, la organización puede disponer de evidencia para revisar el presupuesto semanal de abastecimiento. La investigación no atribuye automáticamente reducciones de merma, cambios de inventario o beneficios financieros, pues tales efectos requieren datos operativos y una evaluación adicional."),
    ("Dado que las series temporales presentan autocorrelación", "Dado que las series semanales presentan autocorrelación, es necesario informar al modelo sobre el pasado reciente. Se construirán rezagos de una, dos, cuatro y ocho semanas, así como medias móviles de cuatro, ocho y doce semanas; cuando la cobertura lo permita, se considerará el rezago estacional de 52 semanas."),
    ("La demanda de Cup&Cake presenta fuerte dependencia del día", "La demanda semanal de Cup&Cake puede presentar dependencia de la semana del año y del mes. La ingeniería de características puede codificar estos ciclos mediante transformaciones seno-coseno, evitando interpretar como distantes periodos temporalmente adyacentes."),
    ("La inclusión del conocimiento empírico del dueño es crítica", "La inclusión del conocimiento empírico del dueño es útil para identificar eventos comerciales y fechas de pago. Estas variables sólo deben utilizarse cuando sean conocidas antes de la semana pronosticada; de esta forma, contribuyen al modelo sin introducir fuga de información."),
    ("Validación Temporal Estricta: Metodología de Ventanas Deslizantes (Rolling-Origin)", "Validación temporal estricta mediante rolling-window (ventana deslizante)"),
    ("Para garantizar la estabilidad predictiva", "Para garantizar la estabilidad predictiva en la planeación semanal, la evaluación debe respetar el orden cronológico y evitar la validación cruzada aleatoria. La estrategia seleccionada es rolling-window (ventana deslizante): el modelo se entrena con una cantidad fija de semanas recientes y se evalúa en la semana posterior."),
    ("Deslizamiento Temporal: El origen del tiempo", "Deslizamiento temporal: la ventana avanza una semana; se incorpora la semana recién observada y se excluye la más antigua, manteniendo constante el tamaño de entrenamiento."),
    ("Para contrarrestar estos obstáculos, el diseño predictivo", "Para contrarrestar estos obstáculos, el diseño predictivo debe regirse por parsimonia, regularización, ingeniería de características y validación estricta. La simulación mediante rolling-window (ventana deslizante) permite comprobar si el desempeño se sostiene al actualizar el conjunto de entrenamiento con información reciente."),
    ("En la ciencia de datos contemporánea, y de manera obligatoria", "En la ciencia de datos contemporánea, la precisión debe evaluarse estrictamente fuera de muestra mediante rolling-window (ventana deslizante). El modelo se juzga por su capacidad para estimar semanas futuras que no formaron parte de su entrenamiento."),
    ("Para la investigación de la microempresa Cup&Cake, la evaluación", "Para la investigación de Cup&Cake, la evaluación del desempeño debe establecer si existe una configuración predictiva con menor error que la regla empírica de referencia y si las variables exógenas aportan información adicional. Las métricas principales serán RMSE y MAE, complementadas con una métrica escalada; MAPE se utilizará sólo como diagnóstico condicionado a la ausencia de problemas por valores cero."),
    ("La superioridad del MAE radica", "El MAE es útil por su interpretabilidad: se expresa en las mismas unidades monetarias del importe semanal de compras y comunica el error promedio sin penalizar de forma desproporcionada los valores extremos."),
    ("Esta característica es invaluable para el proceso", "Esta característica permite interpretar la desviación promedio del presupuesto semanal. No obstante, el estudio no calcula inventario de seguridad ni cantidades físicas de compra, porque no dispone de recetas, existencias, tiempos de entrega ni costos de faltante."),
    ("La justificación de la inclusión del RMSE", "La inclusión del RMSE se justifica porque penaliza con mayor intensidad los errores grandes, relevantes para la reserva del presupuesto semanal. Su interpretación debe limitarse a la precisión predictiva, sin inferir por sí misma pérdidas, mermas o riesgo de quiebra."),
    ("El RMSE es altamente sensible a estos fallos", "El RMSE es sensible a errores atípicos. Cuando dos modelos presentan MAE similar pero RMSE diferente, el modelo con RMSE menor incurre en menos desviaciones grandes; esta información complementa, pero no sustituye, la revisión operativa de los pronósticos."),
    ("Error Porcentual Absoluto Medio (MAPE) y la Relatividad Comercial", "MAPE como métrica diagnóstica en series con valores cero"),
    ("Una de las limitaciones intrínsecas tanto del MAE", "MAE y RMSE dependen de la escala, por lo que se complementarán con una métrica escalada, como MASE o RMSSE. En una serie semanal de compras con valores cero o importes reducidos, las métricas porcentuales pueden ser inestables y no deben ser el criterio principal de selección."),
    ("Para subsanar esta asimetría, la industria ha adoptado", "El MAPE expresa el error como porcentaje, pero su cálculo requiere valores reales distintos de cero. Por esta razón, en esta investigación se reportará sólo como diagnóstico complementario cuando su interpretación sea válida."),
    ("Makridakis S., Spiliotis E. y Assimakopoulos", "Las métricas porcentuales pueden resultar atractivas para comunicar resultados; sin embargo, no sustituyen las métricas absolutas ni escaladas en series intermitentes. La comparación principal se sustentará en RMSE, MAE y la métrica escalada seleccionada."),
    ("No obstante, el investigador debe ser epistemológicamente", "El investigador debe considerar las limitaciones matemáticas del MAPE. Cuando el valor observado es cero, la medida es indefinida; además, es sensible ante valores muy pequeños y puede sesgar la comparación entre modelos."),
    ("A pesar de estas limitaciones, la aplicación del MAPE", "Por estas limitaciones, MAPE no se utilizará para aceptar o rechazar hipótesis ni para seleccionar el modelo ganador. Su función será exclusivamente diagnóstica y se informará junto con una advertencia sobre la presencia de valores cero."),
    ("Validación de Modelos en Series Temporales: Metodología de Ventanas Deslizantes (Rolling-Origin Cross-Validation)", "Validación de modelos semanales mediante rolling-window (ventana deslizante)"),
    ("Para mitigar este problema, la literatura especializada", "Para mitigar este problema, se utilizará rolling-window (ventana deslizante), una evaluación temporal que conserva un tamaño fijo de entrenamiento y desplaza la ventana al incorporar la semana más reciente y retirar la más antigua. Este esquema respeta la asimetría temporal y reproduce las condiciones de actualización continua del negocio."),
    ("El mecanismo de ventanas deslizantes opera", "El mecanismo rolling-window (ventana deslizante) opera con una ventana fija de 52 semanas, un horizonte principal de una semana y un desplazamiento de una semana. El horizonte de cuatro semanas se analizará de forma complementaria para consolidar el presupuesto mensual."),
    ("Definición de la ventana de entrenamiento inicial", "Definición de la ventana de entrenamiento: cada modelo se ajusta con las 52 semanas inmediatamente anteriores al periodo de prueba."),
    ("Pronóstico sobre el horizonte de prueba", "Pronóstico sobre el horizonte de prueba: el modelo genera la estimación para la semana siguiente; de forma complementaria, se evaluará un bloque de cuatro semanas."),
    ("Deslizamiento del origen temporal", "Deslizamiento temporal: después de observar la semana pronosticada, la ventana avanza una semana, incorpora dicho dato y excluye la semana más antigua."),
    ("Reentrenamiento y repetición", "Reentrenamiento y repetición: el modelo se ajusta nuevamente con la ventana actualizada y el ciclo se repite hasta agotar los periodos de evaluación."),
    ("Dentro de esta metodología, Tashman", "La característica definitoria del rolling-window es conservar un tamaño de entrenamiento fijo. Esta decisión prioriza los patrones recientes y permite evaluar la adaptación del modelo ante cambios en ventas, compras, precios o comportamiento comercial."),
    ("Ventana expansiva (Expanding Window)", "La ventana expansiva se reconoce como una alternativa metodológica, pero no se utilizará en el diseño principal porque incorpora de forma permanente datos antiguos que pueden no representar la operación reciente de la microempresa."),
    ("Ventana deslizante de tamaño fijo (Rolling Window)", "Ventana deslizante de tamaño fijo o rolling-window: al incorporar una semana reciente se descarta la más antigua, manteniendo constante el tamaño de muestra. En esta investigación se empleará una ventana de 52 semanas para favorecer la adaptación a condiciones recientes sin perder un ciclo anual completo."),
    ("En el contexto de la planeación financiera e inventarios", "En el contexto de la planeación presupuestal semanal, rolling-window permite estimar el error promedio en múltiples periodos de prueba simulados. Las métricas resultantes representan el desempeño esperado cuando el modelo se actualiza de forma continua con la información disponible."),
    ("El desarrollo de un marco analítico corporativo maduro", "La evaluación del desempeño predictivo no debe descansar en una única métrica. RMSE y MAE permiten valorar, respectivamente, los errores grandes y la desviación promedio; una métrica escalada facilita la comparación contra la línea base, mientras que MAPE se mantiene como diagnóstico condicionado."),
    ("Demostrar la reducción matemática del error", "La comparación de errores mediante este marco experimental permite valorar si existe una mejora predictiva frente a la regla empírica. La simulación con rolling-window (ventana deslizante) evita que las métricas dependan de una única partición temporal."),
    ("La integración de la metodología de Ventanas Deslizantes", "La integración de rolling-window (ventana deslizante) reduce el riesgo de fuga de información al forzar a los modelos a usar únicamente semanas anteriores para estimar semanas futuras. Así se evalúa su capacidad de generalización bajo incertidumbre semanal."),
    ("No obstante, el aporte medular de este marco conceptual", "No obstante, el aporte medular de este marco conceptual es el establecimiento de un diseño de implementación riguroso adaptado a escenarios de Small Data. Para mitigar la dimensionalidad y el sobreajuste, la arquitectura propuesta combina parsimonia, regularización, selección de características y validación mediante rolling-window (ventana deslizante)."),
]
for prefix, text in marco_replacements:
    set_text(find(prefix), text)

stats_anchor = find("Cuando las organizaciones enfrentan patrones de demanda")
insert_after(stats_anchor, "En la escala semanal, ETS, ARIMA y SARIMA constituyen referencias estadísticas para modelar nivel, tendencia y estacionalidad. Si persisten semanas con importe igual a cero, se evaluarán métodos para demanda intermitente, como Croston, SBA y TSB, siempre que sean compatibles con la variable objetivo y la disponibilidad de datos.", "Normal")
insert_after(stats_anchor, "En series con compras intermitentes, el pronóstico puede descomponerse en dos preguntas: si ocurrirá una compra y cuál será su importe condicionado a que ocurra. El modelo hurdle estima ambas partes por separado y las combina como valor esperado semanal. Esta alternativa se evaluará junto con modelos directos y variantes log1p; su utilidad se juzgará únicamente mediante errores fuera de muestra y no se presumirá por su mayor complejidad.", "Normal")

ml_anchor = find("El Paradigma del Aprendizaje Automático")
insert_after(ml_anchor, "Para la comparación semanal se considerarán modelos parsimoniosos y trazables: regresión Ridge o Lasso, Random Forest y XGBoost o LightGBM. Estos algoritmos pueden incorporar rezagos, promedios móviles, calendario y variables exógenas; su valor deberá demostrarse frente a las líneas base y modelos estadísticos, no asumirse por su complejidad.", "Normal")

# Metodología: se reemplaza la escala diaria por semanal y se especifica rolling-window.
metodologia_replacements = [
    ("Se trata de una investigación centrada en evaluar un mecanismo", "Se trata de una investigación centrada en evaluar un mecanismo concreto: el uso de modelos estadísticos y de aprendizaje automático para pronosticar semanalmente el importe de compras de una microempresa de repostería creativa. El ámbito es específico y delimitado; no busca explicar una amplia variedad de situaciones ni atribuir causalidad sobre ingresos, sino contrastar precisión predictiva en un caso de estudio."),
    ("En este sentido, la investigación persigue un fin utilitario", "La investigación tiene un fin aplicado: evaluar si modelos predictivos y un tablero de inteligencia de negocios pueden apoyar la planeación semanal del presupuesto de abastecimiento de Cup&Cake. El estudio no busca generalizar resultados a todas las microempresas ni sustituir el juicio del responsable, sino ofrecer evidencia reproducible para un caso específico."),
    ("La investigación profundiza en como actualmente", "La investigación examina cómo el propietario estima empíricamente las compras y compara esa práctica con pronósticos semanales basados en datos. El propósito es valorar si una estimación de una a cuatro semanas aporta información más precisa para reservar y revisar el presupuesto de abastecimiento."),
    ("Atendiendo a la naturaleza de los datos recolectados", "Atendiendo a la naturaleza de los datos recolectados y procesados, la investigación se fundamenta en un enfoque cuantitativo. Los registros diarios se transforman en una serie semanal de compras y en predictores históricos y exógenos, con el propósito de entrenar y comparar modelos de pronóstico."),
    ("En el escenario operativo de Cup&Cake, este enfoque", "En el escenario operativo de Cup&Cake, el enfoque se operacionaliza mediante la integración de registros históricos de ventas y compras, agregados por semana calendario. También se incorporan variables exógenas disponibles antes de cada pronóstico, tales como eventos comerciales, calendario, inflación vigente y condiciones climáticas definidas sin utilizar información futura."),
    ("La transformación de estos registros en matrices", "La transformación de estos registros en matrices semanales permite contrastar líneas base, modelos estadísticos y algoritmos supervisados. La evaluación se apoyará en RMSE, MAE y una métrica escalada, mientras que MAPE se reportará sólo como diagnóstico condicionado por la presencia de valores cero. Los hallazgos serán verificables y reproducibles dentro del alcance del caso de estudio, sin pretender generalización estadística amplia."),
    ("En el contexto de esta investigación, el objeto evaluado", "En el contexto de esta investigación, el objeto evaluado es la precisión predictiva del importe semanal de compras. La línea base primaria será el método ingenuo de persistencia o último valor semanal observado: para cada semana futura, el pronóstico será igual al importe registrado en la semana completa inmediatamente anterior. Se conservarán los ceros observados; las ausencias de cobertura y los valores sintéticos se excluirán. El promedio móvil de cuatro semanas y, cuando la cobertura lo permita, el pronóstico ingenuo estacional de 52 semanas se mantendrán como comparadores obligatorios en las mismas ventanas futuras."),
    ("Por consiguiente, el rigor del estudio proviene", "Por consiguiente, el rigor del estudio proviene de la separación temporal estricta, la validación rolling-window (ventana deslizante) y la comparación homogénea contra referencias reproducibles. Estos elementos permiten evaluar generalización predictiva en condiciones históricas, sin afirmar causalidad experimental."),
    ("La comparación se operacionalizó como el contraste", "La comparación se operacionalizará como el contraste entre el error de las líneas base empíricas semanales —último valor, promedio móvil de cuatro semanas e ingenuo estacional cuando proceda— y el error de los modelos predictivos en las mismas semanas futuras. No se emplearán preprueba, posprueba ni grupos de control experimentales."),
    ("La comparación utilizó tres orígenes temporales finales", "La evaluación utilizará rolling-window (ventana deslizante) con 52 semanas de entrenamiento y desplazamiento de una semana. El horizonte principal será h=1; el horizonte complementario h=4 se estimará de forma directa, usando únicamente la información disponible en el origen y las variables exógenas conocidas para la semana objetivo. Las métricas de h=1 y h=4 se reportarán por separado. El consolidado presupuestal de cuatro semanas será la suma de los pronósticos directos h=1, h=2, h=3 y h=4, y no un modelo mensual independiente."),
    ("En el marco de este estudio, el proceso deductivo", "En el marco de este estudio, el proceso deductivo parte de los fundamentos de los modelos de pronóstico y de la evidencia empírica sobre Small Data. La literatura científica indica que el desempeño de los modelos depende de la estructura de la serie, las variables disponibles, el tamaño de la muestra y el protocolo de evaluación. Por ello, no se presupone superioridad de los algoritmos de aprendizaje automático sobre los métodos estadísticos o las reglas empíricas."),
    ("Para someter a prueba esta ley general", "Para contrastar las hipótesis, H1 evaluará principalmente en h=1 si alguna configuración estadística o de aprendizaje automático presenta menor error cuadrático que la línea base de último valor semanal observado; H2 comparará configuraciones equivalentes con y sin variables exógenas. El horizonte h=4 se examinará de manera complementaria, sin mezclar sus métricas con h=1. Las diferencias se examinarán sobre los errores fuera de muestra generados por rolling-window (ventana deslizante). Para H1 se aplicará una prueba Diebold-Mariano unilateral con corrección de muestra finita; como se comparan varias configuraciones frente a la misma referencia, los valores p se ajustarán mediante el procedimiento Holm. H1 sólo se considerará respaldada si al menos una configuración mantiene una diferencia favorable y un valor p ajustado no mayor a 0.05."),
    ("La investigación fue longitudinal y retrospectiva", "La investigación es longitudinal y retrospectiva porque utiliza registros diarios de ventas y compras entre 2022 y 2026, agregados posteriormente por semana calendario. La cobertura efectiva de cada objetivo se delimitará antes del modelado; en particular, el análisis de compras sólo utilizará semanas para las que existan registros observados."),
    ("Para dar cumplimiento a los objetivos de la investigación", "Para dar cumplimiento a los objetivos de la investigación, el desarrollo operativo se divide en fases secuenciales: recolección, depuración, agregación semanal, ingeniería de características, modelado, validación rolling-window (ventana deslizante) y comunicación de resultados para el presupuesto de abastecimiento."),
    ("Esta estructuración permitirá transformar el empirismo", "Después de depurar y homologar los registros, las observaciones se agregarán por semana calendario. Esta estructuración permitirá construir una serie objetivo semanal y predictores compatibles con la frecuencia de decisión del presupuesto de abastecimiento."),
    ("Se diseñarán variables temporales y exógenas", "Se diseñarán variables semanales y exógenas que capturen patrones cíclicos y eventos conocidos antes del pronóstico, como número de días festivos, proximidad de fechas comerciales, calendario, INPC vigente y temperatura agregada o pronosticada. No se utilizarán valores observados de una semana futura como predictores."),
    ("Para garantizar la parsimonia y mitigar", "Para garantizar parsimonia y mitigar el sobreajuste asociado a una muestra semanal limitada, se evaluará un conjunto compacto de alternativas estadísticas y de aprendizaje automático:"),
    ("Modelos Estadísticos de Línea Base:", "Modelos estadísticos: se evaluarán ETS, ARIMA, Croston-SBA y TSB. Los dos últimos se incluyen porque separan la frecuencia y el tamaño de los eventos de compra cuando la serie semanal contiene ceros."),
    ("Modelos Supervisados de Aprendizaje Automático:", "Modelos de aprendizaje automático: se evaluarán Ridge, Random Forest e HistGradientBoosting con variables históricas, calendáricas y exógenas disponibles al momento de pronosticar. También se compararán variantes con transformación log1p del importe, que atenúan la influencia de picos al ajustar y revierten la escala al pronosticar."),
    ("Redes Neuronales: Finalmente, se explorará", "Redes neuronales: RNN y LSTM podrán evaluarse como contraste secundario. Su inclusión no presupone una ventaja, debido al número limitado de observaciones semanales y al riesgo de sobreajuste."),
    ("Al tratarse de series de tiempo financieras", "Al tratarse de series temporales, una partición aleatoria clásica invalidaría el orden cronológico. Por ello, se aplicará rolling-window (ventana deslizante) con una ventana fija de 52 semanas."),
    ("Este método consiste en fijar un punto temporal", "En cada iteración, el modelo se entrenará con las 52 semanas inmediatamente anteriores y pronosticará la semana siguiente. La ventana avanzará una semana, incorporando el dato más reciente y excluyendo el más antiguo. El ajuste de hiperparámetros se realizará únicamente con información previa a cada periodo de prueba para evitar fuga de información."),
    ("La evaluación comparativa de los modelos algorítmicos", "La evaluación comparativa calculará la discrepancia entre el importe semanal observado y el pronosticado. H1 se contrastará frente a las líneas base; H2 se evaluará mediante pares de configuraciones equivalentes con y sin variables exógenas."),
    ("MAE (Error Absoluto Medio):", "MAE (Error Absoluto Medio): medirá la magnitud promedio de los errores en el importe semanal de compras, sin considerar su dirección."),
    ("RMSE (Raíz del Error Cuadrático Medio):", "RMSE (Raíz del Error Cuadrático Medio): penalizará con mayor severidad las desviaciones grandes y será el criterio principal de comparación, junto con MAE."),
    ("MAPE (Error Porcentual Absoluto Medio):", "MASE o RMSSE: permitirán expresar el error de forma escalada respecto de una referencia ingenua. MAPE se reportará sólo como diagnóstico complementario cuando los valores cero no impidan su interpretación."),
    ("La fase final del diseño metodológico consiste", "La fase final del diseño metodológico consiste en comunicar los resultados del modelo seleccionado mediante un tablero de inteligencia de negocios. El tablero mostrará el pronóstico de una a cuatro semanas, el consolidado mensual, el modelo utilizado, las métricas de error, las variables exógenas consideradas y las advertencias de cobertura."),
    ("Esta plataforma funcionará como el Sistema de Soporte", "Esta plataforma funcionará como sistema de soporte a la decisión para revisar y reservar el presupuesto de abastecimiento. No generará órdenes automáticas, cantidades físicas por insumo ni simulaciones de expansión comercial, pues esas funciones requieren inventario, recetas, costos y tiempos de entrega que no forman parte del presente estudio."),
]
for prefix, text in metodologia_replacements:
    set_text(find(prefix), text)

coverage_anchor = find("La investigación es longitudinal y retrospectiva porque utiliza registros diarios de ventas y compras entre 2022 y 2026")
insert_after(coverage_anchor, "Cuando se identifique una cola de semanas sin cobertura de compras, dichas semanas se tratarán como ausencia de observación y no como importes cero. Cualquier extensión sintética se almacenará en un archivo independiente, con una etiqueta de procedencia, semilla y método de generación. Sus valores podrán utilizarse únicamente en análisis de sensibilidad o pruebas técnicas del sistema de soporte a la decisión; se excluirán del ajuste, la selección de modelos, la evaluación fuera de muestra y el contraste de H1 y H2.", "Normal")
insert_after(coverage_anchor, "Para asegurar la reproducibilidad, las rutas de datos y resultados se resolverán desde la ubicación del proyecto, sin depender de una carpeta fija del equipo. Cada ejecución exportará un manifiesto con las huellas de las fuentes y del código, versiones de las bibliotecas, semilla aleatoria, parámetros de ventana y diccionario de variables. Este diccionario documentará la fuente, el rezago y la disponibilidad temporal de cada predictor; los indicadores publicados u observados se desplazarán para representar únicamente la información disponible antes del pronóstico.", "Normal")
insert_after(coverage_anchor, "La incorporación de variables exógenas se controlará mediante un registro explícito de fuente, disponibilidad y rezago. El pipeline sólo admitirá predictores incluidos en dicho registro; cualquier variable exógena no documentada se bloqueará antes del modelado. El sistema de soporte a la decisión comunicará este inventario como condición para generar pronósticos futuros, evitando utilizar información que no esté disponible ex ante.", "Normal")

# Desarrollo, resultados, discusión y conclusiones: se sustituyen los textos
# heredados de la evaluación diaria por evidencia del pipeline semanal Rev40.
development_results_replacements = [
    ("Con 07_modelos_estadisticos_ml_rolling_origin.py", "La evaluación operativa se ejecuta con 06_modelos_rolling_window.py. Este módulo compara referencias empíricas, ETS, ARIMA, Croston-SBA, TSB y configuraciones de Ridge, Random Forest e HistGradientBoosting. La ventana deslizante conserva 52 semanas de entrenamiento; los hiperparámetros se ajustan en orígenes temporales previos a los 16 orígenes reservados para evaluación."),
    ("En conjunto, esta secuencia genera tres representaciones comparables", "En conjunto, el pipeline semanal genera un conjunto de modelado trazable, selecciona predictores a partir de cada ventana de entrenamiento y conserva predicciones, métricas, contrastes y un manifiesto de ejecución. El objetivo es comparar precisión fuera de muestra, no reproducir el esquema diario heredado de conjuntos completo, reducido y PCA."),
    ("La línea base representó una referencia empírica reproducible", "La referencia primaria es la persistencia del último importe semanal observado. Como comparadores obligatorios se conservan el promedio móvil de cuatro semanas y el ingenuo estacional de 52 semanas. La comparación se realiza en las mismas semanas y contra la misma ventana de entrenamiento, sin equiparar la línea base con un grupo de control ni atribuir causalidad experimental."),
    ("La ingeniería de características transformó las series originales", "La ingeniería de características semanal incorpora rezagos, medias móviles, codificación cíclica y variables exógenas registradas. Toda variable histórica se construye con información anterior al origen; para pronósticos directos a más de una semana, las características históricas se congelan en el origen y sólo se admiten exógenas disponibles para la semana objetivo."),
    ("Se compararon enfoques empíricos, ARIMA/SARIMA", "Se comparan referencias empíricas, ETS, ARIMA, Croston-SBA, TSB y modelos de aprendizaje automático parsimoniosos. Las variantes log1p y hurdle se mantienen para manejar picos e intermitencia. RNN y LSTM no forman parte de la evidencia principal semanal, debido al número limitado de observaciones y a su riesgo de sobreajuste."),
    ("La evaluación se ejecutó mediante Rolling-Origin.", "La evaluación se ejecuta mediante rolling-window (ventana deslizante) con 52 semanas fijas de entrenamiento, desplazamiento de una semana y 16 orígenes finales comunes. Las métricas se calculan por separado para h=1 y h=4. Para el consolidado presupuestal se suman los pronósticos directos h=1, h=2, h=3 y h=4; esta suma no se interpreta como un modelo mensual independiente."),
    ("El tablero desarrollado para Cup&Cake funciona", "El archivo de salida para el sistema de soporte a la decisión comunica resultados semanales auditables: métricas por horizonte, contrastes H1 y H2, predicciones históricas, consolidaciones de cuatro semanas y el inventario de variables exógenas admitidas. Su propósito es facilitar la revisión humana del presupuesto, no sustituirla."),
    ("Los resultados consolidados se incorporan al tablero", "La integración se realiza mediante 04_dss_semanal.json, generado a partir de la última ejecución del pipeline. El archivo conserva la relación entre cada configuración, las métricas por horizonte, los contrastes estadísticos y las variables exógenas registradas; por ello, evita presentar resultados heredados de un esquema diario como si fueran evidencia semanal actual."),
    ("El flujo de integración puede resumirse de la siguiente manera", "El flujo de integración parte de la ejecución semanal reproducible, exporta predicciones y métricas por horizonte, construye el consolidado h=1+h=2+h=3+h=4 y comunica las advertencias de cobertura y disponibilidad ex ante. La interfaz que consuma esta salida debe actualizarse junto con cada nueva ejecución; de otro modo, sólo representa una instantánea histórica."),
    ("La interfaz permite seleccionar cuatro objetivos", "Para esta investigación, la salida del DSS se limita al importe semanal de compras. Debe mostrar por separado el desempeño en h=1 y h=4, el presupuesto consolidado de cuatro semanas y las variables exógenas registradas. No debe mezclar los resultados del pipeline semanal con los indicadores diarios heredados."),
    ("Como indicadores principales, el tablero muestra", "Los indicadores principales son RMSE, MAE y métricas escaladas por horizonte, junto con la línea base primaria de último valor semanal observado. MAPE se conserva sólo como diagnóstico para observaciones distintas de cero. La aceptación de H1 requiere una prueba Diebold-Mariano unilateral favorable con ajuste Holm no mayor a 0.05; una reducción descriptiva de RMSE por sí sola no es suficiente."),
    ("La visualización central compara el RMSE del modelo", "La visualización central debe comparar rankings y errores de h=1 y h=4 en paneles separados. El consolidado de cuatro semanas se presenta como una suma de pronósticos directos, con sus importes observados y pronosticados, para que el usuario no lo interprete como una estimación mensual independiente."),
    ("Para los objetivos de ventas, el tablero identifica", "La evidencia semanal actual no analiza objetivos diarios de ventas. El DSS no debe conservar conclusiones de modelos de ventas generadas por el pipeline diario heredado, pues no responden a la pregunta de investigación ni al horizonte semanal definido."),
    ("En compras, los resultados favorecen a Random Forest", "En el horizonte principal h=1, Ridge con variables históricas obtuvo el menor RMSE descriptivo (502.11) y MAE de 325.98. La referencia primaria de último valor semanal observado registró RMSE de 595.02 y MAE de 400.19. Esta diferencia descriptiva se reporta junto con el contraste inferencial, sin convertirla automáticamente en confirmación de H1."),
    ("La conclusión global presentada por el DSS", "La conclusión del DSS es prudente: ningún contraste frente a la línea base primaria fue significativo después del ajuste Holm, tanto en h=1 como en h=4. Por ello, el sistema comunica los modelos con menor error descriptivo como alternativas exploratorias y conserva la referencia empírica como comparación obligatoria."),
    ("El DSS traduce cada resultado en una recomendación operativa", "El DSS debe apoyar la revisión del presupuesto y mostrar la incertidumbre asociada a cada horizonte. En h=1 puede comunicarse Ridge histórico como el menor RMSE descriptivo; en h=4, el promedio móvil de cuatro semanas obtuvo el menor RMSE descriptivo (652.52). Ninguno de estos resultados autoriza automatizar compras ni afirmar superioridad estadísticamente demostrada."),
    ("La cobertura temporal se presenta como una condición de uso", "La cobertura se presenta como una condición de uso: después de depurar la cola sin observación, quedaron 135 semanas con compras observadas y se excluyeron 43 semanas sin cobertura. Los datos sintéticos se mantienen fuera del ajuste y de los contrastes. Antes de utilizar el sistema con fines operativos, deben actualizarse las fuentes y repetirse la evaluación."),
    ("El pipeline se completó sin errores.", "El pipeline semanal se ejecutó con 135 semanas observadas de compras; una cola de 43 semanas sin cobertura se excluyó como ausencia de observación y no como importe cero. La evaluación utilizó una ventana de entrenamiento de 52 semanas y 16 orígenes temporales finales comunes. Los datos sintéticos se conservaron en un archivo independiente y no participaron en el ajuste, la evaluación ni los contrastes de hipótesis."),
    ("El perfil inicial identificó 271 predictores.", "El conjunto semanal de modelado integra características históricas, cíclicas y exógenas con disponibilidad documentada. La selección se realiza dentro de cada ventana de entrenamiento y se limita a un máximo de 15 predictores; este criterio favorece parsimonia e interpretabilidad ante el tamaño muestral disponible."),
    ("Las arquitecturas RNN y LSTM no superaron", "Las arquitecturas RNN y LSTM no se utilizaron como evidencia principal en la evaluación semanal. Con 135 semanas observadas, se priorizaron modelos estadísticos y de aprendizaje automático parsimoniosos; las redes recurrentes se reservan como comparación secundaria para una futura ampliación de la cobertura."),
    ("La hipótesis H1 estableció una reducción mínima de 20 %", "H1 se contrastó principalmente en h=1 contra la línea base de último valor semanal observado. Aunque Ridge histórico mostró el menor RMSE descriptivo en h=1 (502.11 frente a 595.02 de la referencia), ninguna configuración presentó una diferencia significativa después de la prueba Diebold-Mariano unilateral con ajuste Holm. En h=4 tampoco se obtuvieron contrastes significativos. En consecuencia, H1 no queda respaldada con la evidencia disponible; el resultado debe comunicarse como comparación descriptiva y no como demostración de superioridad."),
    ("El tablero integró los modelos ganadores", "El DSS integra métricas y predicciones de validación por horizonte, el consolidado de cuatro semanas, los contrastes H1 y H2 y el registro de variables exógenas. Las salvaguardas comunican cobertura, disponibilidad ex ante y el carácter histórico de los resultados. La interfaz debe mantener la decisión final bajo responsabilidad de la persona usuaria."),
    ("ARIMA fue la familia ganadora para ambos objetivos", "Los resultados se reportan exclusivamente para el importe semanal de compras. En h=1, Ridge histórico obtuvo el menor RMSE descriptivo; en h=4, el promedio móvil de cuatro semanas obtuvo el menor RMSE descriptivo. La MAPE se mantiene como indicador secundario debido a la presencia de semanas con importe cero."),
    ("La superioridad de ARIMA en ventas indica", "Los hallazgos no respaldan una superioridad general de un modelo complejo. En h=1, Ridge histórico mostró el menor RMSE descriptivo; en h=4, una referencia empírica simple resultó competitiva. Esta diferencia entre horizontes refuerza la necesidad de informar métricas separadas y de no trasladar conclusiones de un horizonte a otro."),
    ("El resultado de RNN y LSTM muestra", "La evaluación refuerza que una arquitectura más compleja no implica mayor precisión. La muestra semanal limitada, la intermitencia y la heterogeneidad de las compras justifican mantener alternativas parsimoniosas y referencias empíricas como controles permanentes."),
    ("La proporción de días con valor cero", "La serie semanal conserva episodios con importe cero y picos de compra, por lo que MAPE puede ser inestable o no estar definido en algunas semanas. Las conclusiones se sustentan principalmente en RMSE, MAE y métricas escaladas; MAPE se presenta sólo como diagnóstico condicionado a valores observados distintos de cero."),
    ("La evidencia permite priorizar el uso predictivo en compras", "La evidencia permite utilizar los pronósticos como apoyo exploratorio para revisar el presupuesto de compras, pero no para automatizar decisiones. La ausencia de significancia tras Holm implica que la referencia de último valor semanal debe seguir acompañando cualquier recomendación. Tampoco es posible inferir reducciones efectivas de faltantes, sobreabastecimiento o merma sin datos de inventario, recetas y tiempos de entrega."),
    ("La validez interna se fortaleció", "La validez interna se fortaleció mediante orden temporal, ventana fija, exclusión de cobertura ausente, bloqueo de datos sintéticos y control explícito de disponibilidad de exógenas. La validez externa permanece limitada por tratarse de una sola microempresa, 135 semanas observadas y 16 orígenes finales. Estos límites explican la interpretación conservadora de los contrastes de hipótesis."),
    ("Se construyó una solución analítica reproducible", "Se construyó una solución semanal reproducible que integra registros de compras, características históricas y variables exógenas registradas. El proceso compara modelos mediante rolling-window, separa h=1 y h=4, genera un consolidado de cuatro semanas y comunica los resultados en un DSS auditable."),
    ("La hipótesis se respaldó para el presupuesto", "La evidencia no respalda H1 bajo el criterio inferencial predefinido: aunque Ridge histórico redujo descriptivamente el RMSE en h=1, ninguna configuración superó el contraste Diebold-Mariano con ajuste Holm. En h=4, una línea base de promedio móvil fue la alternativa con menor RMSE descriptivo. Por ello, no se afirma superioridad general de los modelos estadísticos o de aprendizaje automático frente a la referencia primaria."),
    ("El estudio también demuestra que, en un contexto de Small Data", "El estudio muestra que, en un contexto de Small Data e intermitencia, la parsimonia, la calidad de las variables, la disponibilidad ex ante y la validación temporal son más relevantes que la complejidad algorítmica. La ausencia de respaldo de H1 también constituye conocimiento útil: impide recomendar un modelo como superior sin evidencia suficiente."),
    ("Se recomienda actualizar mensualmente las fuentes", "Se recomienda actualizar semanalmente los registros de compras y ejecutar nuevamente el pipeline antes de usar pronósticos operativos. Debe conservarse la línea base de último valor como referencia, revisar por separado h=1 y h=4 y comunicar el consolidado sólo como suma de cuatro pronósticos semanales. Las decisiones deben incluir revisión humana y límites financieros."),
    ("Como trabajo futuro, conviene registrar inventario inicial", "Como trabajo futuro, conviene ampliar la cobertura observada de compras, registrar inventario inicial y final, recetas, merma, costo de faltante y tiempos de entrega; además, realizar validación prospectiva y analizar si los resultados se sostienen con más orígenes de prueba. También puede evaluarse un modelo mensual independiente únicamente cuando exista una serie mensual suficiente y una necesidad de decisión claramente diferenciada."),
]
for prefix, text in development_results_replacements:
    set_text(find(prefix), text)

performance_heading = find("Rendimiento comparativo de los modelos")
performance_h1 = insert_after(performance_heading, "La evaluación comparativa se reporta por horizonte. En h=1, Ridge con variables históricas registró RMSE de 502.11 y MAE de 325.98, frente a RMSE de 595.02 y MAE de 400.19 de la persistencia del último valor semanal observado. En h=4, el promedio móvil de cuatro semanas fue la alternativa con menor RMSE descriptivo (652.52) y MAE de 427.63. Las métricas no se combinan entre horizontes.", "Normal")
insert_after(performance_h1, "Para la planeación de cuatro semanas, el pipeline suma las estimaciones directas h=1, h=2, h=3 y h=4. Esta salida se conserva como consolidado presupuestal histórico y no equivale a un modelo mensual independiente. La comparación incluye 21 configuraciones en 16 orígenes comunes, con 336 registros consolidados.", "Normal")

document.save(OUTPUT)
print(OUTPUT)
